name: my-cicd
run-name: ${{ github.actor }} Actions Part 2
on: 
  push: 
    branches: [ main ] 
    paths: 
    - 'factorial.py' 
    - 'myfunc.py' 
    - 'test_factorial.py' 
 jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.10.6
    - name: Install dependencies 
      run: | 
        python3 -m pip install --upgrade pip 
        pip install pytest 
     - name: Lint with Pytest
      run: | 
        pytest myfunc.py 
     - name: Run pytest suite 
     run: | 
        pytest test_factorial.py 