name: my-cicd
run-name: ${{ github.actor }} Actions Part 2
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with: 
        python-version: 3.12.0-alpha.7
    - run: python3 -m pip install --upgrade pip 
    - run: pip install pytest 
    - run: pytest myfunc.py 
    - run: pytest test_factorial.py 
